# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.box = "enzzito/mykubuntu2204-gui"
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "vagrant-vm"

  config.vm.provision "shell", path: "provisioning.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "kubuntu-22.04-vagrant"
    vb.memory = "4096" # 4GB
    vb.cpus = 2

    vb.customize [ 'modifyvm', :id, '--graphicscontroller', 'vmsvga']
    vb.customize [ 'modifyvm', :id, '--groups', '/Templates']
    vb.customize [ 'modifyvm', :id, '--ostype', 'Ubuntu']
    vb.customize [ 'modifyvm', :id, '--audioout', 'on']
    vb.customize [ 'modifyvm', :id, '--clipboard-mode', 'hosttoguest']
    vb.customize [ 'modifyvm', :id, '--description', 'Teste de Descrição']

  end

end
